---
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Set teiserver running fact
  ansible.builtin.set_fact:
    teiserver_running: '{{ "teiserver.service" in services and services["teiserver.service"]["state"] == "running" }}'
- name: Create postgres database
  community.postgresql.postgresql_db:
    name: '{{ database_name }}'
    encoding: UTF-8
- name: Create postgres user
  community.postgresql.postgresql_user:
    name: '{{ database_user }}'
    password: '{{ database_password }}'
    role_attr_flags: SUPERUSER
- name: Grant privileges
  community.postgresql.postgresql_privs:
    type: database
    database: '{{ database_name }}'
    roles: '{{ database_user }}'
    privs: ALL
- name: Custom HBA rules
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/15/main/pg_hba.conf
    rules:
      - contype: local
        databases: '{{ database_name }}'
        users: '{{ database_user }}'
        method: trust
- name: Enable pg_stat_statements module
  # We have to do this one first, because without it the pg_stat_statements.track
  # setting will not be available in the next step.
  community.postgresql.postgresql_set:
    name: shared_preload_libraries
    value: pg_stat_statements
  register: pg_shared_preload_libraries
- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql@15-main.service
    state: restarted
  when: pg_shared_preload_libraries.changed and not teiserver_running
  become_user: root
- name: Tune Postgresql configuration
  community.postgresql.postgresql_set:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  loop:
    - name: track_activity_query_size
      value: '2kB'  # For some reason 2048 showed constantly as diff in ansible module
    - name: pg_stat_statements.track
      value: 'all'
    - name: log_min_duration_statement
      value: '5s'
  register: pstune
- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql@15-main.service
    state: restarted
  become_user: root
  when: pstune.results | selectattr('changed') | map(attribute='restart_required') is any and not teiserver_running
- name: Print note about restart
  ansible.builtin.debug:
    msg: "WARNING: Changes required postgresql restart, but teiserver is running. Please handle manually."
  when: teiserver_running and (pg_shared_preload_libraries.changed or pstune.results | selectattr('changed') | map(attribute='restart_required') is any)
- name: Enabled pg_stat_statements extension
  community.postgresql.postgresql_ext:
    name: pg_stat_statements
    db: '{{ database_name }}'
