---
- name: Set timezone to UTC
  community.general.timezone:
    name: Etc/UTC
- name: Set hostname
  ansible.builtin.hostname:
    name: "teiserver-{{ inventory_hostname }}"
- name: Install packages
  ansible.builtin.package:
    name:
      - acl  # for ansible become
      - acmetool
      - build-essential
      - curl
      - dnsutils
      - geoip-bin
      - git
      - grc
      - htop
      - jq
      - lz4
      - man
      - nano
      - nginx
      - podman
      - podman-docker
      - postgresql-15
      - python3-psycopg2  # for ansible postgresql
      - rclone  # for backups
      - ssl-cert  # self-signed cert for testing
      - tcpdump
      - tmux
      - ufw
      - unzip
      - vim
      - xz-utils
      - zstd
    state: present
- name: Install gum
  ansible.builtin.apt:
    deb: https://github.com/charmbracelet/gum/releases/download/v0.13.0/gum_0.13.0_amd64.deb
- name: Add deploy user
  ansible.builtin.user:
    name: deploy
    shell: /bin/bash
    groups:
      - sudo
    append: true
    password: '!'  # Disable password login
- name: Don't require password for sudo for deploy user
  ansible.builtin.copy:
    content: |
      deploy ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/90-deploy-user
    mode: '0440'
- name: Make sure podman resolves docker.io correctly wihout prefix
  ansible.builtin.lineinfile:
    path: /etc/containers/registries.conf
    regexp: '^unqualified-search-registries '
    insertafter: '^# unqualified-search-registries'
    line: "unqualified-search-registries = ['docker.io']"
- name: Create podman-auto-update.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/podman-auto-update.service.d
    state: directory
    recurse: true
    mode: '0755'
- name: Create podman-auto-update.service.d/01-longer-prune.conf
  ansible.builtin.copy:
    content: |
      # We expand the prune time to 10 days so that build cache
      # is not pruned every 24h with the default value.
      [Service]
      ExecStartPost=
      ExecStartPost=/usr/bin/podman image prune -f --filter until=240h
    dest: /etc/systemd/system/podman-auto-update.service.d/01-longer-prune.conf
    mode: '0644'
- name: Allow git to run on any directory
  ansible.builtin.copy:
    content: |
      [safe]
        directory = *
    dest: /etc/gitconfig
    mode: '0644'
