#!/bin/bash

set -e -u -o pipefail

PROD_DATA="/home/deploy/prod-data"

TARGET_DIR="${1-}"
if [ -z "$TARGET_DIR" ]; then
  echo "Usage: $0 <teiserver-repo-path>"
  exit 1
fi

FA_TMP="$(mktemp -d)"
function cleanup {
  rm -rf "$FA_TMP"
}
trap cleanup EXIT

set -x

# Prod secrets
cp "$PROD_DATA/prod.secret.exs" "$TARGET_DIR/config/prod.secret.exs"

# Release vm args
mkdir -p "$TARGET_DIR/rel"
cp "$PROD_DATA/vm.args.eex" "$TARGET_DIR/rel/vm.args.eex"

# Fontawesome
unzip -o -j "$PROD_DATA/fontawesome.zip" '*css/all.min.css' '*webfonts/*' -d "$FA_TMP"
cp "$FA_TMP/all.min.css" "$TARGET_DIR/priv/static/css/fontawesome.css"
mkdir -p "$TARGET_DIR/priv/static/webfonts"
cp "$FA_TMP"/*.ttf "$FA_TMP"/*.woff2 "$TARGET_DIR/priv/static/webfonts/"
