#!/bin/bash

set -e -u -o pipefail
. /usr/local/lib/bash/shflags
. /usr/local/lib/bash/tei-bash-lib

FLAGS_HELP="USAGE: $(basename $0) [flags]

List teiserver releases.
"
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

_tei_list_versions | gum table -c version,time,actor,commit,repo,tags -p
