#!/bin/bash

set -e -u -o pipefail
. /usr/local/lib/bash/shflags
. /usr/local/lib/bash/tei-bash-lib

DEFINE_string 'tag' '' 'Name of the tag to remove' 't'
DEFINE_boolean 'skip_confirmation' false 'Skip deploy confirmation prompt' 'y'
FLAGS_HELP="USAGE: $(basename $0) [flags]

Untag a teiserver release.
"
FLAGS "$@" || exit $?
_tei_ensure_root "$@"
eval set -- "${FLAGS_ARGV}"

cd $_TEI_INSTALL_DIR
_tei_lock_deploy

tag="${FLAGS_tag}"
if [[ -z "$tag" ]]; then
    tag=$(_tei_list_tags \
        | cut -f1 \
        | grep -v -E '^latest|live|rollback$' \
        | gum filter --height=10 --sort --placeholder="Tag to remove...")
fi

if [[ $tag =~ ^latest|live|rollback$ ]]; then
    gum style --bold "Cannot remove reserved tag $tag"
    exit 1
elif [[ ! -L $tag ]]; then
    gum style --bold "Tag $tag does not exist"
    exit 1
fi

if [[ "${FLAGS_skip_confirmation}" == "${FLAGS_FALSE}" ]] \
  && ! gum confirm "Are to sure you want to remove tag $tag?"; then
    exit 0
fi

rm $tag
gum style --bold "Removed tag $tag"
