#!/bin/bash

set -e -u -o pipefail
. /usr/local/lib/bash/shflags

PROD_DATA="/home/deploy/prod-data"

FLAGS_HELP="USAGE: $(basename $0) [flags] <teiserver-repo-path>

Apply production data from $PROD_DATA to the specified teiserver repo path.
"
FLAGS "$@" || exit $?
eval set -- "${FLAGS_ARGV}"

TARGET_DIR="${1-}"
if [ -z "$TARGET_DIR" ]; then
  echo "ERROR: Missing teiserver repo path"
  flags_help
  exit 1
fi

FA_TMP="$(mktemp -d)"
function cleanup {
  rm -rf "$FA_TMP"
}
trap cleanup EXIT

set -x

# Prod secrets
cp "$PROD_DATA/prod.secret.exs" "$TARGET_DIR/config/prod.secret.exs"

# Release vm args
mkdir -p "$TARGET_DIR/rel"
cp "$PROD_DATA/vm.args.eex" "$TARGET_DIR/rel/vm.args.eex"

# Fontawesome
unzip -o -j "$PROD_DATA/fontawesome.zip" '*css/all.min.css' '*webfonts/*' -d "$FA_TMP"
cp "$FA_TMP/all.min.css" "$TARGET_DIR/priv/static/css/fontawesome.css"
mkdir -p "$TARGET_DIR/priv/static/webfonts"
cp "$FA_TMP"/*.ttf "$FA_TMP"/*.woff2 "$TARGET_DIR/priv/static/webfonts/"
