---
- name: Reload systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: reloaded
- name: Restart Dex
  ansible.builtin.systemd_service:
    name: dex.service
    state: restarted
